package com.jew.test.model;

import com.jew.plugin.activeRecord.ActiveRecordPlugin;
/**
* Generated by Jew, do not modify this file.
*<pre>
* Example:
* public void configPlugin(Plugins me) {
*			ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
*       	_MappingKit.mapping(arp);
*       	me.add(arp);
* }
* </pre>
*/
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("Signature", "id", Signature.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("iptables", "id", Iptables.class);
		arp.addMapping("link", "id", Link.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("sweetWords", "id", SweetWords.class);
		arp.addMapping("tag", "id", Tag.class);
	}
}