package com.jew.test.model;

import com.jew.test.model.base.BaseBlog;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog>{
	public static final Blog dao = new Blog();

}
