package com.jew.test.model;

import com.jew.test.model.base.BaseComment;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment>{
	public static final Comment dao = new Comment();

}
