package com.jew.test.model;

import com.jew.test.model.base.BaseIptables;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Iptables extends BaseIptables<Iptables>{
	public static final Iptables dao = new Iptables();

}
