package com.jew.test.model;

import com.jew.test.model.base.BaseLink;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Link extends BaseLink<Link>{
	public static final Link dao = new Link();

}
