package com.jew.test.model;

import com.jew.test.model.base.BaseMenu;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu>{
	public static final Menu dao = new Menu();

}
