package com.jew.test.model;

import com.jew.test.model.base.BaseSignature;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Signature extends BaseSignature<Signature>{
	public static final Signature dao = new Signature();

}
