package com.jew.test.model;

import com.jew.test.model.base.BaseSweetWords;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class SweetWords extends BaseSweetWords<SweetWords>{
	public static final SweetWords dao = new SweetWords();

}
