package com.jew.test.model;

import com.jew.test.model.base.BaseTag;

/**
* Generated by Jew.
*/
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag>{
	public static final Tag dao = new Tag();

}
