package com.jew.plugin.activeRecord.generator;
//package com.forum.common.model;
//
//import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
//
///**
// * Generated by JFinal, do not modify this file.
// * <pre>
// * Example:
// * public void configPlugin(Plugins me) {
// *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
// *     _MappingKit.mapping(arp);
// *     me.add(arp);
// * }
// * </pre>
// */
//public class _MappingKit {
//
//	public static void mapping(ActiveRecordPlugin arp) {
//		arp.addMapping("Signature", "id", Signature.class);
//		arp.addMapping("blog", "id", Blog.class);
//		arp.addMapping("comment", "id", Comment.class);
//		arp.addMapping("iptables", "id", Iptables.class);
//		arp.addMapping("link", "id", Link.class);
//		arp.addMapping("menu", "id", Menu.class);
//		arp.addMapping("sweetWords", "id", SweetWords.class);
//		arp.addMapping("tag", "id", Tag.class);
//	}
//}

import java.util.List;

import com.jew.kit.FileKit;

/**
 * MappingKitGenerator
 */
public class MappingKitGenerator {
	
	private String mappingKitDir ;
	private String mappingKitPackageDir;
	private static final String packageStr = "package %s;%n%n";
	private static final String importStr = "import com.jew.plugin.activeRecord.ActiveRecordPlugin;%n";
	private static final String commStr = "/**%n" +
										   "* Generated by Jew, do not modify this file.%n" +
										   "*<pre>%n" +
										   "* Example:%n" +
										   "* public void configPlugin(Plugins me) {%n" +
										   "*		\tActiveRecordPlugin arp = new ActiveRecordPlugin(...);%n" + 
										   "*       \t_MappingKit.mapping(arp);%n" + 
										   "*       \tme.add(arp);%n" +
										   "* }%n" + 
										   "* </pre>%n" + 
										   "*/%n";
	private static final String classHead = "public class _MappingKit {%n%n"+
										   "\tpublic static void mapping(ActiveRecordPlugin arp) {%n";
	private static final String classBody = "\t\tarp.addMapping(\"%s\", \"%s\", %s);%n";
	
	private static final String classTail = "\t}%n}";
	
	public MappingKitGenerator(String mappingKitDir,String mappingKitPackageDir){
		this.mappingKitDir = mappingKitDir;
		this.mappingKitPackageDir = mappingKitPackageDir;
	}
	
	public void generate(List<TableMeta> tabMetaList){
		gen(tabMetaList);
	}
	
	private void gen(List<TableMeta> tmList){
		
		StringBuilder sb = new StringBuilder();
		genPackageStr(sb);
		genImportStr(sb);
		genCommStr(sb);
		genClassHead(sb);
		genClassBody(tmList,sb);
		genClassTail(sb);
		
		FileKit.writeFile(mappingKitDir, "_MappingKit.java", sb.toString(), true);
	}
	
	private void genClassBody(List<TableMeta> tmList,StringBuilder sb){
		for(TableMeta tm : tmList){
			sb.append(String.format(classBody, tm.name,tm.primaryKeys,tm.modelName +".class"));
		}
	}
	
	private void genClassTail(StringBuilder sb){
		sb.append(String.format(classTail));
	}
	
	private void genClassHead(StringBuilder sb){
		sb.append(String.format(classHead));
	}
	
	private void genCommStr(StringBuilder sb){
		sb.append(String.format(commStr));
	}
	
	private void genPackageStr( StringBuilder sb){
		sb.append(String.format(packageStr,mappingKitPackageDir));
	}
	
	private void genImportStr(StringBuilder sb){
		sb.append(String.format(importStr));
	}
	
	
}
