package com.jew.plugin.activeRecord.generator;

import java.util.List;

import com.jew.kit.FileKit;

/**
 * ModelGenerator
 */
public class ModelGenerator {
//	package com.forum.common.model;
//
//	import java.util.List;
//
//	import com.forum.common.model.base.BaseLink;
//
	/**
	 * Generated by JFinal.
	 */
//	@SuppressWarnings("serial")
//	public class Link extends BaseLink<Link> {
//		public static final Link dao = new Link();
//		
//		public List<Link> findAll(){
//			return dao.find("select * from link");
//		}
//	}	
	private String modelPackageName;
	private String modelOutputDir;
	
	private String packageStr = "package %s;%n%n";
	private String importStr = "import %s;%n%n";
	private String headStr = "/**%n"+
							  "* Generated by Jew.%n"+
							  "*/%n"+ 
							  "@SuppressWarnings(\"serial\")%n" + 
							  "public class %s extends %s<%s>{%n";
	private String bodyStr = "\tpublic static final %s dao = new %s();%n%n";
	
	public ModelGenerator(String modelOutputDir,String modelPackageName){
		this.modelOutputDir = modelOutputDir;
		this.modelPackageName = modelPackageName;
	}
	
	public void generate(List<TableMeta> tabMetaList){
		for(TableMeta tm : tabMetaList){
			genModel(tm);
			writeToFile(tm);
		}
	}
	
	private void writeToFile(TableMeta tm){
		FileKit.writeFile(modelOutputDir, tm.modelName+".java",tm.modelContent,false);
	}
	
	private void genModel(TableMeta tm){
		StringBuilder sb = new StringBuilder();
		genPackageStr(sb);
		genImportStr(tm,sb);
		genHeadStr(tm,sb);
		genBody(tm,sb);
		genTail(sb);
		tm.modelContent = sb.toString();
	}
	
	private void genTail(StringBuilder sb){
		sb.append("}\n");
	}
	
	private void genPackageStr(StringBuilder sb){
		sb.append(String.format(packageStr,modelPackageName));
	}
	
	private void genImportStr(TableMeta tm,StringBuilder sb){
		sb.append(String.format(importStr,modelPackageName +".base.Base" + tm.modelName));
	}
	
	private void genHeadStr(TableMeta tm,StringBuilder sb){
		sb.append(String.format(headStr, tm.modelName , "Base"+tm.modelName,tm.modelName));
	}
	
	private void genBody(TableMeta tm , StringBuilder sb){
		sb.append(String.format(bodyStr, tm.modelName,tm.modelName));
	}
	
}
