package com.jew.test.model.base;

import com.jew.plugin.activeRecord.Model;
import com.jew.plugin.activeRecord.IBean;

/**
 * Generated by Jew, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLink<M extends BaseLink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}
	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}
	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}
}
