package com.jew.test.model.base;

import com.jew.plugin.activeRecord.Model;
import com.jew.plugin.activeRecord.IBean;

/**
 * Generated by Jew, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSweetWords<M extends BaseSweetWords<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}
	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}
}
