package com.jew.test.model.base;

import com.jew.plugin.activeRecord.Model;
import com.jew.plugin.activeRecord.IBean;

/**
 * Generated by Jew, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
	public void setAuthorId(java.lang.Integer authorId) {
		set("author_id", authorId);
	}

	public java.lang.Integer getAuthorId() {
		return get("author_id");
	}
	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}
	public void setReadTime(java.lang.Integer readTime) {
		set("readTime", readTime);
	}

	public java.lang.Integer getReadTime() {
		return get("readTime");
	}
	public void setSortId(java.lang.Integer sortId) {
		set("sort_id", sortId);
	}

	public java.lang.Integer getSortId() {
		return get("sort_id");
	}
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}
	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}
	public void setIsHotLog(java.lang.String isHotLog) {
		set("isHotLog", isHotLog);
	}

	public java.lang.String getIsHotLog() {
		return get("isHotLog");
	}
	public void setThumbUp(java.lang.Integer thumbUp) {
		set("thumbUp", thumbUp);
	}

	public java.lang.Integer getThumbUp() {
		return get("thumbUp");
	}
	public void setThumbDown(java.lang.Integer thumbDown) {
		set("thumbDown", thumbDown);
	}

	public java.lang.Integer getThumbDown() {
		return get("thumbDown");
	}
}
